### ISSUE TITLE
File operation: Let Fortran code about delete operation be portable

### ISSUE THREAD

**Issue by sean0921** [sean0921/timeseries_process#9]
- ref: https://stackoverflow.com/questions/18668832/how-delete-file-from-fortran-code/18671521

## Tasks
- [x] check which part can apply this concept and fix
- [x] fix it and commit
- [ ] check if CI passed

**Comment by sean0921** [comment]
for e.g.

```fortran
        out1='ts_'//sta(i)//'_n_b.dat'
        out2='ts_'//sta(i)//'_e_b.dat'
        out3='ts_'//sta(i)//'_u_b.dat'
        out4='ts_'//sta(i)//'_b.dat'

        open(12,file=inp)
        open(13,file=out1)
        open(14,file=out2)
        open(15,file=out3)
        open(16,file=out4)

        write(16,'(a)')'year doy      hr       dn      sn      de      se      dh      sh (unit: mm)'

        n=0
        avgn=0.
        avge=0.
        avgh=0.
        stat=0
        do while (stat==0)
          read(12,*,iostat=stat)
          if(stat/=0) exit
          n=n+1
        end do
        if(n==1) then
          jud=1
          close(12)
          close(13)
          close(14)
          close(15)
          close(16)
#ifdef PLATFORM_IS_WINDOWS
          temp='del '//out1//' '//out2//' '//out3//' '//out4//' '//inp
          call system(temp)
#else
          temp='rm -f '//out1//' '//out2//' '//out3//' '//out4//' '//inp
          call system(temp)
#endif
```

should be 

```fortran
        out1='ts_'//sta(i)//'_n_b.dat'
        out2='ts_'//sta(i)//'_e_b.dat'
        out3='ts_'//sta(i)//'_u_b.dat'
        out4='ts_'//sta(i)//'_b.dat'

        open(12,file=inp)
        open(13,file=out1)
        open(14,file=out2)
        open(15,file=out3)
        open(16,file=out4)

c ...something

        if(n==1) then
          close(12)
          close(13,status='delete')
          close(14,status='delete')
          close(15,status='delete')
          close(16,status='delete')
        endif

c ...something

        close(12,status='delete')
        close(13)
        close(14)
        close(15)
        close(16)
```
